import { Product, Sale, InventoryMovement, DashboardStats } from "@/types";

export const mockStats: DashboardStats = {
  totalProducts: 184,
  totalStockValue: 12_450_000,
  lowStockCount: 7,
  outOfStockCount: 2,
  todaySales: 143_500,
  periodSales: 2_180_000,
};

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "iPhone 13 128GB",
    sku: "APL-IP13-128",
    category: "Phones",
    brand: "Apple",
    unit: "unit",
    costPrice: 420000,
    sellingPrice: 495000,
    stockQty: 14,
    reorderLevel: 5,
    status: "in-stock",
  },
  {
    id: "p2",
    name: "Samsung A14 64GB",
    sku: "SAM-A14-64",
    category: "Phones",
    brand: "Samsung",
    unit: "unit",
    costPrice: 110000,
    sellingPrice: 138000,
    stockQty: 3,
    reorderLevel: 5,
    status: "low-stock",
  },
  {
    id: "p3",
    name: "Anker 20W Charger",
    sku: "ANK-CH20",
    category: "Accessories",
    brand: "Anker",
    unit: "unit",
    costPrice: 8500,
    sellingPrice: 12000,
    stockQty: 0,
    reorderLevel: 10,
    status: "out-of-stock",
  },
  {
    id: "p4",
    name: "Tecno Spark 10",
    sku: "TEC-SPK10",
    category: "Phones",
    brand: "Tecno",
    unit: "unit",
    costPrice: 95000,
    sellingPrice: 118000,
    stockQty: 22,
    reorderLevel: 8,
    status: "in-stock",
  },
  {
    id: "p5",
    name: "Screen Protector (Universal)",
    sku: "ACC-SP-U",
    category: "Accessories",
    brand: "Generic",
    unit: "unit",
    costPrice: 500,
    sellingPrice: 1500,
    stockQty: 4,
    reorderLevel: 20,
    status: "low-stock",
  },
];

export const mockRecentSales: Sale[] = [
  {
    id: "s1",
    reference: "SL-1042",
    customerName: "Chidi Okafor",
    items: 1,
    subtotal: 495000,
    discount: 0,
    total: 495000,
    paymentStatus: "paid",
    createdAt: "2026-09-05T09:12:00Z",
  },
  {
    id: "s2",
    reference: "SL-1041",
    customerName: "Walk-in customer",
    items: 3,
    subtotal: 13500,
    discount: 1500,
    total: 12000,
    paymentStatus: "paid",
    createdAt: "2026-09-05T08:40:00Z",
  },
  {
    id: "s3",
    reference: "SL-1040",
    customerName: "Aisha Bello",
    items: 1,
    subtotal: 138000,
    discount: 0,
    total: 138000,
    paymentStatus: "partial",
    createdAt: "2026-09-04T17:05:00Z",
  },
];

export const mockMovements: InventoryMovement[] = [
  {
    id: "m1",
    productId: "p2",
    productName: "Samsung A14 64GB",
    type: "stock-out",
    quantity: 1,
    reason: "Sale SL-1040",
    actor: "Aisha (Cashier)",
    createdAt: "2026-09-04T17:05:00Z",
  },
  {
    id: "m2",
    productId: "p4",
    productName: "Tecno Spark 10",
    type: "stock-in",
    quantity: 15,
    reason: "Purchase PO-203",
    actor: "Musa (Manager)",
    createdAt: "2026-09-04T11:20:00Z",
  },
  {
    id: "m3",
    productId: "p3",
    productName: "Anker 20W Charger",
    type: "adjustment",
    quantity: -2,
    reason: "Damaged in storage",
    actor: "Musa (Manager)",
    createdAt: "2026-09-03T15:00:00Z",
  },
];
